include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:
    unawaited_futures: false
    directives_ordering: false
    combinators_ordering: false
    sort_pub_dependencies: false
    public_member_api_docs: false
    sort_constructors_first: false
    require_trailing_commas: false
    unnecessary_raw_strings: false
    always_use_package_imports: false
    lines_longer_than_80_chars: false
    no_adjacent_strings_in_list: false
    use_setters_to_change_properties: false
    avoid_positional_boolean_parameters: false
    missing_whitespace_between_adjacent_strings: false
