name: guardian_keyper
description: "A Guardian Network-based secrets backup app"
publish_to: 'none'

version: 2.0.3

environment:
  sdk: ">=2.19.2 <3.0.0"
  flutter: ^3.7.10

dependencies:
  flutter:
    sdk: flutter
  double_back_to_close_app: ^2.1.0
  # logging_appenders: ^1.0.2
  vector_graphics: ^1.1.5
  google_fonts: ^4.0.3
  flutter_svg: ^2.0.5
  messagepack: ^0.2.1
  equatable: ^2.0.5
  provider: ^6.0.5
  # logging: ^1.1.1
  get_it: ^7.2.0
  p2plib: ^1.1.2
  sss256: ^1.0.0
  intl: ^0.18.0
  qr_flutter:
    git:
      url: "https://github.com/theyakka/qr.flutter"

  # Platform dependent
  flutter_secure_storage: ^8.0.0
  flutter_screen_lock: ^9.0.1
  connectivity_plus: ^3.0.4
  device_info_plus: ^8.2.0
  mobile_scanner: ^3.2.0
  url_launcher: ^6.1.10
  hive_flutter: ^1.1.0
  sodium_libs: ^2.1.0+1
  local_auth: ^2.1.5
  share_plus: ^6.3.2
  vibration: ^1.7.6
  wakelock: ^0.6.2
  sodium: ^2.1.0
  nsd: ^2.3.1

  # Analytics
  sentry_flutter: ^7.4.2
  amplitude_flutter: ^3.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
