name: guardian_keyper
description: "A Guardian Network-based secrets backup app"
publish_to: 'none'

version: 2.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"
  flutter: ^3.7.3

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.0+1
  google_fonts: ^4.0.3
  intl: ^0.17.0
  provider: ^6.0.5
  equatable: ^2.0.5
  messagepack: ^0.2.1
  sss256: ^1.0.0
  double_back_to_close_app: ^2.1.0
  qr_flutter: # ^4.0.0
    git:
      url: "https://github.com/theyakka/qr.flutter"

  # Platform dependent
  flutter_launcher_icons: ^0.11.0
  flutter_secure_storage: ^8.0.0
  flutter_native_splash: ^2.2.16
  flutter_screen_lock: ^9.0.0+1
  airplane_mode_checker: ^1.0.3
  hive_flutter: ^1.1.0
  bonsoir: ^2.0.0
  wakelock: ^0.6.2
  local_auth: ^2.1.3
  mobile_scanner: ^3.0.0
  share_plus: ^6.3.1
  connectivity_plus: ^3.0.3
  package_info_plus: ^3.0.3
  device_info_plus: ^8.1.0
  # network_info_plus: ^3.0.2
  app_settings: ^4.2.0
  vibration: ^1.7.6
  sodium_libs: ^2.0.0

  # Analytics
  amplitude_flutter: ^3.13.0
  sentry_flutter: ^6.20.1

  # P2P networking
  p2plib:
    path: "../p2plib-dart"
    # git:
      # url: "https://github.com/alexandrim0/p2plib-dart.git"
      # url: "https://github.com/GuardianLabs/p2plib-dart.git"
      # ref: "v0.9.2"

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/

flutter_icons:
  android: true
  ios: true
  image_path_ios: "assets/images/logo1024.png"
  image_path_android: "assets/images/logo512.png"

flutter_native_splash:
  color: "#1A0244"
  color_dark: "#1A0244"
  image: assets/images/4.0x/logo.png
  image_dark: assets/images/4.0x/logo.png
  android_gravity: center
  fullscreen: true
