name: guardian_network
description: A Guardian Network client
publish_to: 'none'

version: 0.1.2+1

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ^2.10.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2
  flutter_native_splash: ^2.0.1+1
  google_fonts: ^2.2.0
  flutter_svg: ^1.0.3
  provider: ^6.0.2
  qr_flutter: ^4.0.0
  qr_code_scanner: ^0.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    - assets/images/
    - assets/icons/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo512.png"
  remove_alpha_ios: true

flutter_native_splash:
  color: "#1A0244"
  color_dark: "#1A0244"
  image: assets/images/4.0x/logo.png
  image_dark: assets/images/4.0x/logo.png
  android_gravity: center
  fullscreen: true