name: guardian_keyper
description: "A Guardian Network-based secrets backup app"
publish_to: 'none'

version: 2.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  vector_graphics: ^1.1.6
  google_fonts: ^4.0.4
  flutter_svg: ^2.0.6
  messagepack: ^0.2.1
  collection: ^1.17.1
  qr_flutter: ^4.1.0
  provider: ^6.0.5
  get_it: ^7.6.0
  p2plib: ^2.0.0
  sss256: ^1.0.0
  intl: ^0.18.0

  # Platform dependent
  flutter_secure_storage: ^8.0.0
  flutter_screen_lock: ^9.0.1
  connectivity_plus: ^3.0.6
  device_info_plus: ^8.2.0
  mobile_scanner: ^3.2.0
  url_launcher: ^6.1.11
  hive_flutter: ^1.1.0
  sodium_libs: ^2.1.0+1
  local_auth: ^2.1.6
  share_plus: ^6.3.4
  vibration: ^1.7.7
  wakelock: ^0.6.2
  sodium: ^2.1.0
  nsd: ^2.3.1

  # Analytics
  sentry_flutter: ^7.6.1
  amplitude_flutter: ^3.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
