name: guardian_keyper
description: "A Guardian Network-based secrets backup app"
publish_to: 'none'

version: 2.2.8

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ^3.22.0

dependencies:
  flutter:
    sdk: flutter
  vector_graphics: ^1.1.11
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10
  messagepack: ^0.2.1
  collection: ^1.18.0
  qr_flutter: ^4.1.0
  provider: ^6.1.2
  get_it: ^7.7.0
  p2plib: ^2.2.1
  sss256: ^1.0.0
  intl: ^0.19.0

  # Platform dependent
  flutter_secure_storage: ^9.2.2
  flutter_screen_lock: ^9.1.0
  connectivity_plus: ^6.0.3
  device_info_plus: ^10.1.0
  mobile_scanner: ^5.1.1
  path_provider: ^2.1.3
  wakelock_plus: ^1.2.5
  url_launcher: ^6.3.0
  sodium_libs: ^2.2.1
  local_auth: ^2.2.0
  share_plus: ^9.0.0
  vibration: ^1.9.0
  sodium: ^2.3.1
  hive: ^2.2.3
  nsd: ^3.0.0

  # Analytics
  sentry_flutter: ^8.3.0
  amplitude_flutter: ^3.16.2

dependency_overrides:

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
