name: guardian_keyper
description: "A Guardian Network-based secrets backup app"
publish_to: 'none'

version: 2.2.1

environment:
  sdk: ">=3.2.0 <4.0.0"
  flutter: ^3.16.4

dependencies:
  flutter:
    sdk: flutter
  vector_graphics: ^1.1.9+1
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  messagepack: ^0.2.1
  collection: ^1.17.2
  qr_flutter: ^4.1.0
  provider: ^6.1.1
  get_it: ^7.6.4
  p2plib: ^2.1.1
  sss256: ^1.0.0
  intl: ^0.18.1

  # Platform dependent
  flutter_secure_storage: ^9.0.0
  flutter_screen_lock: ^9.0.1
  connectivity_plus: ^5.0.2
  device_info_plus: ^9.1.1
  mobile_scanner: ^3.5.5
  path_provider: ^2.1.1
  wakelock_plus: ^1.1.4
  sodium_libs: ^2.2.0+6
  url_launcher: ^6.2.1
  local_auth: ^2.1.7
  share_plus: ^7.2.1
  vibration: ^1.8.4
  sodium: ^2.3.0
  hive: ^2.2.3
  nsd: ^3.0.0

  # Analytics
  sentry_flutter: ^7.13.2
  amplitude_flutter: ^3.16.1

dependency_overrides:

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
