name: guardian_keyper
description: "A Guardian Network-based secrets backup app"
publish_to: 'none'

version: 1.1.2+1

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ^3.3.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_launcher_icons: ^0.10.0
  flutter_native_splash: ^2.2.9
  flutter_secure_storage: ^6.0.0
  flutter_screen_lock: ^7.0.4
  flutter_svg: ^1.1.5
  google_fonts: ^3.0.1
  amplitude_flutter: ^3.2.1
  sentry_flutter: ^6.11.1
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  intl: ^0.17.0
  provider: ^6.0.3
  event_bus: ^2.0.0
  equatable: ^2.0.5
  messagepack: ^0.2.1
  # qr_flutter: ^4.0.0
  qr_flutter:
    git:
      url: "https://github.com/theyakka/qr.flutter"

  # Crypto
  sodium_libs: ^1.2.5
  sss256: ^1.0.0

  # Platform specific
  wakelock: ^0.6.2
  bonsoir: ^2.0.0
  local_auth: ^2.1.2
  mobile_scanner: ^2.0.0
  share_plus: ^4.1.0
  connectivity_plus: ^2.3.6+1
  package_info_plus: ^1.4.3+1
  device_info_plus: ^4.1.2
  airplane_mode_checker: ^1.0.2
  app_settings: ^4.1.8
  vibration: ^1.7.6

  # P2P networking
  p2plib:
    git:
      url: "https://github.com/GuardianLabs/p2plib-dart.git"
      ref: "v0.9.2"

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/

flutter_icons:
  android: true
  ios: true
  image_path_ios: "assets/images/logo1024.png"
  image_path_android: "assets/images/logo512.png"

flutter_native_splash:
  color: "#1A0244"
  color_dark: "#1A0244"
  image: assets/images/4.0x/logo.png
  image_dark: assets/images/4.0x/logo.png
  android_gravity: center
  fullscreen: true
