import 'package:guardian_keyper/src/core/consts.dart';
import 'package:guardian_keyper/src/core/ui/widgets/emoji.dart';
import 'package:guardian_keyper/src/core/ui/widgets/common.dart';

import '../presenters/vault_guardian_add_presenter.dart';

class GetCodePage extends StatefulWidget {
  const GetCodePage({super.key});

  @override
  State<GetCodePage> createState() => _GetCodePageState();
}

class _GetCodePageState extends State<GetCodePage> with WidgetsBindingObserver {
  final _errorSnackbar = buildSnackBar(
    text: 'The Code is not valid!\n'
        'Please, make sure if it was generated by Keyper',
    isError: true,
  );

  late final _presenter = context.read<VaultGuardianAddPresenter>();

  @override
  void initState() {
    super.initState();
    WidgetsBinding.instance.addObserver(this);
    _presenter.checkClipboard();
  }

  @override
  void dispose() {
    WidgetsBinding.instance.removeObserver(this);
    super.dispose();
  }

  @override
  void didChangeAppLifecycleState(final AppLifecycleState state) {
    if (state == AppLifecycleState.resumed) _presenter.checkClipboard();
  }

  @override
  Widget build(final BuildContext context) => Column(
        children: [
          // Header
          HeaderBar(
            captionSpans: buildTextWithId(id: _presenter.vaultId),
            closeButton: const HeaderBarCloseButton(),
          ),
          // Body
          PageTitle(
            title: 'Add your Guardians',
            subtitleSpans: [
              TextSpan(
                style: textStyleSourceSansPro616Purple,
                text: 'Add Guardian(s) ',
              ),
              TextSpan(
                style: textStyleSourceSansPro416Purple,
                text: 'to enable your Vault and secure your Secrets.',
              ),
            ],
          ),
          Padding(
            padding: paddingH20,
            child: PrimaryButton(
              text: 'Add via a QR Code',
              onPressed: () => Navigator.of(context)
                  .pushNamed<String?>(routeScanQrCode)
                  .then(
                    (code) => _presenter.parseCode(code, _onError),
                  ),
            ),
          ),
          Padding(
            padding: paddingAll20,
            child: Selector<VaultGuardianAddPresenter, bool>(
              selector: (
                final BuildContext context,
                final VaultGuardianAddPresenter presenter,
              ) =>
                  presenter.canUseClipboard,
              builder: (
                final BuildContext context,
                final bool canUseClipboard,
                final Widget? widget,
              ) =>
                  PrimaryButton(
                text: 'Add via a Text Code',
                onPressed: canUseClipboard
                    ? () => _presenter
                        .getCodeFromClipboard()
                        .then((code) => _presenter.parseCode(code, _onError))
                    : null,
              ),
            ),
          ),
        ],
      );

  void _onError() {
    if (context.mounted) {
      ScaffoldMessenger.of(context).showSnackBar(_errorSnackbar);
    }
  }
}
